name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: |
          composer install --no-scripts --no-progress --no-suggest

      - name: Update Composer dependencies
        run: |
          composer update --no-scripts --no-progress --no-suggest

      - name: Install Node Modules
        run: npm update

      - name: Build the frontend assets
        run: npm run build

      - name: Dump autoload files
        run: composer dump-autoload --optimize

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /
          exclude: |
              .git*
              .gitignored:\htaccessfile\.HTACCESS_PHP.txt
